-- AUTO-GENERATED by scripts/generate-seed.ts — do not edit by hand. Run files in numeric order.
begin;
insert into public.news_posts (slug,title_en,title_ar,meta_title_en,meta_title_ar,excerpt_en,excerpt_ar,body_en,body_ar,cover_image,published_at,is_published) values ($q$how-to-choose-the-right-kva-generator$q$,$q$How to Choose the Right kVA Generator for Your Site$q$,$q$كيف تختار مولد الكهرباء بالقدرة المناسبة (ك.ف.أ) لموقعك$q$,$q$How to Choose the Right kVA Generator Size | 4U Power UAE$q$,$q$كيف تختار حجم المولد المناسب بالكيلو فولت أمبير | فور يو باور$q$,$q$Too small and it trips when the chiller starts; too big and you pay for fuel and wet-stacking. The step-by-step kVA sizing method our engineers use.$q$,$q$المولد الصغير يفصل عند تشغيل التكييف، والكبير يهدر الوقود ويتضرر بالحمل المنخفض. إليك طريقة مهندسينا خطوة بخطوة لاختيار قدرة المولد الصحيحة.$q$,$q$Choosing a generator is mostly a sizing question. Get the kVA right and everything else — price, fuel use, service life — falls into place. Get it wrong and you either trip the breaker every time a motor starts, or you run a large engine at 20% load and slowly damage it.

## Step 1: List what must run on generator power

Walk the site and write down every load that must keep running during an outage: air-conditioning, lifts, pumps, lighting, IT racks, cold rooms, production machines. For each one note the **running power in kW** (from the nameplate) and whether it is a **motor**.

If you only know the current, you can convert it. For a three-phase 400 V supply:

- kW ≈ 1.732 × 400 × amps × power factor ÷ 1000
- As a quick rule, 1 amp per phase at 400 V ≈ 0.69 kVA

## Step 2: Convert kW to kVA

Generators are rated in **kVA** (apparent power) because the alternator must carry the full current regardless of power factor. Your equipment uses **kW** (real power).

**kVA = kW ÷ power factor**

Most mixed commercial and industrial loads sit around 0.8 power factor — which is also the standard rating point for diesel generators. So 160 kW of load needs a 200 kVA generator at minimum.

## Step 3: Allow for motor starting

A direct-on-line motor can draw five to seven times its running current for a few seconds while it starts. The generator must absorb that surge without the voltage collapsing. Soft starters and VFDs cut this dramatically, so always tell us how your large motors are started.

The practical check: running load **plus** the extra starting demand of the largest motor must stay within what the generator can deliver for a few seconds.

## Step 4: Add a safety margin — but not too much

We normally add **20–25%** on top of the calculated running kVA. That margin covers:

- motor starting and inrush from transformers and LED drivers
- the derating needed at 45–50 °C ambient in the Gulf
- modest future growth

Going far beyond that is counter-productive. Diesel engines that run below roughly 30% load for long periods suffer from "wet stacking" — unburnt fuel accumulating in the exhaust — which raises maintenance cost.

## Step 5: Round up to a real product

Generators come in standard ratings (20, 30, 50, 100, 150, 200, 250, 350, 500 kVA and so on). Round up to the nearest one, then decide on engine brand and enclosure. See our [diesel generator range](/en/generators) for the ratings we supply from 10 to 2500 kVA.

## Don't forget the transfer switch

A generator only takes over automatically if it is paired with an **automatic transfer switch**. Size the ATS to the generator's full-load current — roughly kVA × 1.44 at 400 V. Our guide [ATS panels explained](/en/news/ats-panels-explained) covers this in detail.

## Use the calculator, then talk to an engineer

Our free [kVA calculator](/en/calculator) runs through these steps for you and suggests matching units from our catalog. Send the result to us on WhatsApp and an engineer will confirm the selection against your actual load list — usually the same working day.$q$,$q$اختيار المولد هو في الأساس مسألة تحديد الحجم. إذا اخترت القدرة الصحيحة بالكيلو فولت أمبير فإن كل شيء آخر — السعر واستهلاك الوقود وعمر المحرك — يصبح في مكانه. أما إذا أخطأت، فإما أن يفصل القاطع كلما بدأ محرك بالعمل، أو يعمل محرك كبير بحمل 20% فيتضرر تدريجياً.

## الخطوة 1: حدد ما يجب تشغيله على المولد

تجوّل في الموقع واكتب كل حمل يجب أن يستمر أثناء انقطاع الكهرباء: التكييف والمصاعد والمضخات والإنارة وأجهزة الخوادم وغرف التبريد وماكينات الإنتاج. لكل حمل سجّل **القدرة التشغيلية بالكيلوواط** من لوحة البيانات، وهل هو **محرك** أم لا.

إذا كنت تعرف التيار فقط يمكنك التحويل. لتغذية ثلاثية الأطوار 400 فولت:

- الكيلوواط ≈ 1.732 × 400 × الأمبير × معامل القدرة ÷ 1000
- كقاعدة سريعة: كل 1 أمبير لكل طور على 400 فولت ≈ 0.69 ك.ف.أ

## الخطوة 2: حوّل الكيلوواط إلى كيلو فولت أمبير

تُقنن المولدات بالـ **ك.ف.أ** (القدرة الظاهرية) لأن الدينامو يجب أن يتحمل التيار الكامل بغض النظر عن معامل القدرة، بينما تستهلك أجهزتك **كيلوواط** (القدرة الفعلية).

**ك.ف.أ = الكيلوواط ÷ معامل القدرة**

معظم الأحمال التجارية والصناعية المختلطة تكون حول معامل قدرة 0.8، وهو أيضاً نقطة التقنين القياسية لمولدات الديزل. لذلك يحتاج حمل 160 كيلوواط إلى مولد 200 ك.ف.أ كحد أدنى.

## الخطوة 3: احسب تيار بدء المحركات

المحرك الذي يبدأ مباشرة على الخط قد يسحب من خمسة إلى سبعة أضعاف تياره التشغيلي لبضع ثوانٍ. يجب أن يتحمل المولد هذه الزيادة دون انهيار الجهد. أجهزة البدء الناعم ومغيرات السرعة تقلل ذلك كثيراً، لذا أخبرنا دائماً بطريقة تشغيل محركاتك الكبيرة.

الاختبار العملي: الحمل التشغيلي **مضافاً إليه** الطلب الإضافي لبدء أكبر محرك يجب أن يبقى ضمن ما يستطيع المولد توفيره لبضع ثوانٍ.

## الخطوة 4: أضف هامش أمان — دون مبالغة

نضيف عادةً **من 20 إلى 25%** فوق القدرة التشغيلية المحسوبة. هذا الهامش يغطي:

- بدء المحركات وتيار الاندفاع من المحولات ومشغلات الإنارة
- خفض القدرة المطلوب في حرارة 45–50 درجة في الخليج
- التوسع المستقبلي المعقول

تجاوز ذلك بكثير يأتي بنتيجة عكسية؛ فمحركات الديزل التي تعمل تحت 30% من حملها لفترات طويلة تعاني من تراكم الوقود غير المحترق في العادم، ما يرفع تكلفة الصيانة.

## الخطوة 5: اختر أقرب منتج حقيقي

تأتي المولدات بقدرات قياسية (20، 30، 50، 100، 150، 200، 250، 350، 500 ك.ف.أ وهكذا). اختر القدرة الأعلى الأقرب ثم حدد نوع المحرك والهيكل. اطلع على [مولدات الديزل لدينا](/ar/generators) من 10 إلى 2500 ك.ف.أ.

## لا تنسَ لوحة التحويل

لا يتولى المولد التغذية تلقائياً إلا إذا كان مقترناً بـ **لوحة تحويل أوتوماتيكي ATS**. اختر سعة اللوحة حسب تيار الحمل الكامل للمولد — تقريباً ك.ف.أ × 1.44 على 400 فولت. مقالنا [شرح لوحات ATS](/ar/news/ats-panels-explained) يشرح ذلك بالتفصيل.

## استخدم الحاسبة ثم تحدث مع مهندس

[حاسبة القدرة المجانية](/ar/calculator) تنفذ هذه الخطوات وتقترح وحدات مناسبة من الكتالوج. أرسل النتيجة لنا على الواتساب وسيؤكد مهندسنا الاختيار حسب قائمة أحمالك الفعلية، عادةً في نفس يوم العمل.$q$,$q$/images/news/kva-sizing.svg$q$,$q$2026-06-02T08:00:00Z$q$,true) on conflict (slug) do nothing;
insert into public.news_posts (slug,title_en,title_ar,meta_title_en,meta_title_ar,excerpt_en,excerpt_ar,body_en,body_ar,cover_image,published_at,is_published) values ($q$ats-panels-explained$q$,$q$ATS Panels Explained: Why Every Generator Needs One$q$,$q$شرح لوحات ATS: لماذا يحتاج كل مولد إلى لوحة تحويل أوتوماتيكي$q$,$q$ATS Panels Explained: Why Every Generator Needs One | 4U$q$,$q$شرح لوحات ATS ولماذا يحتاجها كل مولد | فور يو باور$q$,$q$What an automatic transfer switch does, how to size an ATS panel for your generator, and the installation mistakes we see most often across the UAE.$q$,$q$المولد بدون لوحة تحويل أوتوماتيكي مجرد محرك ينتظر أن يأتي أحد لتشغيله. ما وظيفة لوحة ATS وكيف تختار سعتها وما الأخطاء الأكثر شيوعاً في الإمارات.$q$,$q$When mains power fails at 2 a.m., who starts the generator? If the answer is "the watchman", your building is running on hope. An **automatic transfer switch (ATS) panel** removes the human from the loop.

## What an ATS actually does

An ATS panel sits between the utility supply, the generator and your main distribution board. Its controller continuously monitors mains voltage and frequency. When it detects a failure it:

1. waits a few seconds to ignore short dips
2. sends a start signal to the generator
3. waits until generator voltage and frequency are stable
4. switches the load from mains to generator
5. when mains returns and stays healthy, switches back and lets the engine cool down before stopping it

The whole sequence normally takes **5–15 seconds**, most of it engine start and warm-up.

## Types of ATS panel

- **Motorised changeover switch** — compact and cost-effective, common from 63 A to about 1600 A.
- **Contactor-based ATS** — simple and fast, suited to smaller ratings.
- **ACB-based changeover** — two interlocked air circuit breakers, used from roughly 630 A to 4000 A where protection and metering are needed too.

## How to size an ATS

Match the ATS rating to the **generator's full-load current**, or the incoming mains breaker if that is larger. At 400 V three-phase:

**Current (A) ≈ kVA × 1.443**

So a 250 kVA generator produces about 361 A, and needs a **400 A** ATS. A 500 kVA set needs about 722 A — so an **800 A** panel.

## 3-pole or 4-pole?

A **4-pole ATS** switches the neutral as well as the phases. It is recommended when the generator's neutral is earthed separately from the utility neutral, and where earth-leakage protection must work correctly on both sources. In many UAE installations 4-pole is the safer default — we confirm against your earthing arrangement.

## Mistakes we see on site

- **ATS sized to the load, not the generator.** When the site grows the ATS becomes the bottleneck.
- **No mechanical interlock.** Both sources must never be connected at the same time.
- **No cool-down timer.** Stopping a hot turbocharged engine immediately shortens its life.
- **Panels without IP protection** installed in dusty plant rooms or outdoors.

## Where to go next

Browse our [ATS panel range](/en/ats-panels) from 63 A to 4000 A, or use the [kVA calculator](/en/calculator), which also recommends the ATS rating for the generator it selects. If you already have a generator, send us its nameplate photo on WhatsApp and we will propose the matching panel.$q$,$q$عندما تنقطع الكهرباء في الثانية فجراً، من سيشغّل المولد؟ إذا كانت الإجابة "الحارس"، فإن مبناك يعمل على الأمل. **لوحة التحويل الأوتوماتيكي ATS** تلغي الحاجة لتدخل الإنسان.

## ماذا تفعل لوحة ATS فعلياً؟

تقع لوحة ATS بين كهرباء الشبكة والمولد ولوحة التوزيع الرئيسية. تراقب وحدة التحكم فيها جهد وتردد الشبكة باستمرار، وعند اكتشاف الانقطاع:

1. تنتظر بضع ثوانٍ لتجاهل الانخفاضات القصيرة
2. ترسل إشارة تشغيل للمولد
3. تنتظر حتى يستقر جهد المولد وتردده
4. تنقل الحمل من الشبكة إلى المولد
5. عند عودة الكهرباء واستقرارها، تعيد الحمل للشبكة وتترك المحرك يبرد قبل إيقافه

يستغرق التسلسل عادةً **من 5 إلى 15 ثانية**، ومعظمها زمن تشغيل المحرك واستقراره.

## أنواع لوحات ATS

- **مفتاح تحويل مُحرّك (Motorised)** — صغير الحجم واقتصادي، شائع من 63 أمبير حتى حوالي 1600 أمبير.
- **ATS بالكونتاكتورات** — بسيط وسريع ومناسب للسعات الصغيرة.
- **تحويل بقواطع ACB** — قاطعان هوائيان متشابكان، يستخدم من حوالي 630 إلى 4000 أمبير عندما تكون الحماية والقياس مطلوبة أيضاً.

## كيف تختار سعة لوحة ATS؟

يجب أن تساوي سعة اللوحة **تيار الحمل الكامل للمولد**، أو قاطع التغذية الرئيسي إن كان أكبر. على 400 فولت ثلاثي الأطوار:

**التيار (أمبير) ≈ ك.ف.أ × 1.443**

فالمولد 250 ك.ف.أ ينتج حوالي 361 أمبير ويحتاج لوحة **400 أمبير**. والمولد 500 ك.ف.أ ينتج حوالي 722 أمبير، أي لوحة **800 أمبير**.

## ثلاثية أم رباعية الأقطاب؟

لوحة **ATS رباعية الأقطاب** تفصل خط التعادل مع الأطوار. ويوصى بها عندما يكون تعادل المولد مؤرضاً بشكل منفصل عن تعادل الشبكة، وعندما يجب أن تعمل حماية التسرب الأرضي بشكل صحيح على المصدرين. في كثير من تركيبات الإمارات تكون الرباعية هي الخيار الأكثر أماناً، ونؤكد ذلك حسب نظام التأريض لديك.

## أخطاء نراها في المواقع

- **اختيار سعة ATS حسب الحمل وليس حسب المولد**، فتصبح اللوحة عنق الزجاجة عند توسع الموقع.
- **عدم وجود تشابك ميكانيكي**؛ يجب ألا يتصل المصدران معاً أبداً.
- **عدم وجود مؤقت تبريد**؛ إيقاف محرك تيربو ساخن فوراً يقصّر عمره.
- **لوحات بدون حماية IP** مركّبة في غرف مغبرة أو في الخارج.

## الخطوة التالية

تصفح [لوحات ATS لدينا](/ar/ats-panels) من 63 إلى 4000 أمبير، أو استخدم [حاسبة القدرة](/ar/calculator) التي تقترح أيضاً سعة لوحة ATS للمولد المختار. إذا كان لديك مولد بالفعل، أرسل لنا صورة لوحة بياناته على الواتساب وسنقترح اللوحة المناسبة.$q$,$q$/images/news/ats-explained.svg$q$,$q$2026-06-16T08:00:00Z$q$,true) on conflict (slug) do nothing;
commit;
