-- AUTO-GENERATED by scripts/generate-seed.ts — do not edit by hand. Run files in numeric order.
begin;
insert into public.news_posts (slug,title_en,title_ar,meta_title_en,meta_title_ar,excerpt_en,excerpt_ar,body_en,body_ar,cover_image,published_at,is_published) values ($q$switchgear-maintenance-checklist$q$,$q$Switchgear Maintenance Checklist for UAE Facilities$q$,$q$قائمة صيانة لوحات الكهرباء للمنشآت في الإمارات$q$,$q$Switchgear Maintenance Checklist for UAE Facilities | 4U$q$,$q$قائمة صيانة لوحات الكهرباء والمفاتيح للمنشآت في الإمارات$q$,$q$Heat, dust and humidity are hard on LV switchgear. A practical monthly, quarterly and annual checklist your facility team can start using today.$q$,$q$الحرارة والغبار والرطوبة تؤثر بشدة على لوحات الجهد المنخفض. قائمة صيانة عملية شهرية وربع سنوية وسنوية يمكن لفريق المنشأة في الإمارات البدء بها اليوم.$q$,$q$Switchgear rarely fails without warning. Loose connections, overheating and dust build-up give plenty of signs — if someone is looking. This checklist is written for facility teams in the UAE, where heat and fine dust accelerate every failure mode.

> Safety first: work inside energised panels must only be carried out by authorised, competent electricians following your site's permit-to-work and lock-out/tag-out procedures.

## Monthly (visual, panels closed)

- Check indicator lamps, meters and alarms on the panel doors
- Listen for buzzing or chattering contactors
- Check the room: temperature, AC operation, no water ingress, doors closed, no storage in front of panels
- Confirm the generator ATS is in **Auto**, not left in Manual after testing

## Quarterly

- **Thermal imaging scan** under load — the single most valuable test. Hot spots on terminals, busbar joints and breakers show loose or overloaded connections before they burn.
- Clean filters on panel ventilation fans
- Test the ATS transfer by simulating mains failure (with the facility's agreement)
- Check earth-leakage and RCD test buttons

## Annually (shutdown required)

- De-energise, isolate and prove dead
- Vacuum dust from busbars and compartments — never use compressed air, it drives dust deeper
- **Torque-check** busbar and cable terminations to manufacturer values
- Inspect insulation for tracking and discolouration
- Exercise and inspect ACB/MCCB mechanisms; test trip units with secondary injection
- Insulation resistance (megger) test
- Update the single-line diagram and panel labels if anything changed

## UAE-specific risks

- **Heat:** every 10 °C rise roughly halves the life of many insulating materials. Keep electrical rooms air-conditioned.
- **Fine dust:** conductive when combined with humidity — especially in coastal areas like Sharjah and Dubai.
- **Condensation:** when an AC fails overnight and restarts, moisture can form inside panels. Anti-condensation heaters help.

## When to upgrade instead of maintain

If breakers are obsolete and spares unavailable, if the panel has been repeatedly extended beyond its busbar rating, or if the building load has grown significantly, replacement is often cheaper than continued repair. We supply [LV switchgear and MDBs](/en/switchgear) configured to your single-line diagram and [ATS panels](/en/ats-panels) for generator changeover.

Send us photos of your existing panels and nameplates on WhatsApp and we will advise whether a retrofit or a new board makes more sense.$q$,$q$نادراً ما تتعطل لوحات الكهرباء دون إنذار. التوصيلات المرتخية وارتفاع الحرارة وتراكم الغبار تعطي علامات كثيرة، إذا كان هناك من يراقبها. هذه القائمة مكتوبة لفرق المنشآت في الإمارات حيث تسرّع الحرارة والغبار الناعم كل أنواع الأعطال.

> السلامة أولاً: أي عمل داخل لوحات موصولة بالكهرباء يجب أن ينفذه كهربائيون مؤهلون ومصرح لهم، وفق إجراءات تصاريح العمل والعزل والتعليق المعتمدة في الموقع.

## شهرياً (فحص بصري واللوحات مغلقة)

- افحص لمبات البيان والعدادات والإنذارات على أبواب اللوحات
- استمع لأي طنين أو اهتزاز في الكونتاكتورات
- افحص الغرفة: درجة الحرارة، عمل التكييف، عدم تسرب المياه، الأبواب مغلقة، لا توجد مواد مخزنة أمام اللوحات
- تأكد أن لوحة ATS للمولد على وضع **أوتوماتيك** وليست متروكة على اليدوي بعد الاختبار

## كل ثلاثة أشهر

- **فحص بالتصوير الحراري** أثناء التحميل، وهو أهم اختبار على الإطلاق. النقاط الساخنة على الأطراف ووصلات القضبان والقواطع تكشف التوصيلات المرتخية أو المحمّلة زيادة قبل أن تحترق.
- تنظيف فلاتر مراوح تهوية اللوحات
- اختبار تحويل ATS بمحاكاة انقطاع الكهرباء (بموافقة إدارة المنشأة)
- فحص أزرار اختبار قواطع التسرب الأرضي

## سنوياً (يتطلب فصل الكهرباء)

- افصل الكهرباء واعزل وتأكد من عدم وجود جهد
- شفط الغبار من القضبان والأقسام — لا تستخدم الهواء المضغوط لأنه يدفع الغبار للداخل
- **فحص عزم الربط** لوصلات القضبان والكابلات حسب قيم الشركة المصنعة
- فحص العوازل بحثاً عن آثار التفريغ أو تغير اللون
- تشغيل وفحص آليات قواطع ACB وMCCB واختبار وحدات الفصل بالحقن الثانوي
- اختبار مقاومة العزل (الميجر)
- تحديث المخطط أحادي الخط وملصقات اللوحات عند أي تغيير

## مخاطر خاصة بالإمارات

- **الحرارة:** كل ارتفاع 10 درجات يقلل عمر كثير من المواد العازلة إلى النصف تقريباً، فحافظ على تكييف غرف الكهرباء.
- **الغبار الناعم:** يصبح موصلاً مع الرطوبة، خاصة في المناطق الساحلية مثل الشارقة ودبي.
- **التكثف:** عندما يتوقف التكييف ليلاً ثم يعود، قد تتكون رطوبة داخل اللوحات، وتساعد سخانات منع التكثف في ذلك.

## متى تستبدل بدلاً من الصيانة؟

إذا كانت القواطع قديمة وقطع غيارها غير متوفرة، أو تم توسيع اللوحة مراراً بما يتجاوز سعة قضبانها، أو زاد حمل المبنى بشكل كبير، فالاستبدال غالباً أوفر من الإصلاح المستمر. نورد [لوحات الجهد المنخفض ولوحات التوزيع](/ar/switchgear) حسب المخطط أحادي الخط، و[لوحات ATS](/ar/ats-panels) لتحويل المولدات.

أرسل لنا صور لوحاتك الحالية ولوحات بياناتها على الواتساب وسننصحك إن كان التحديث أم اللوحة الجديدة هو الخيار الأفضل.$q$,$q$/images/news/switchgear-maintenance.svg$q$,$q$2026-08-05T08:00:00Z$q$,true) on conflict (slug) do nothing;
insert into public.news_posts (slug,title_en,title_ar,meta_title_en,meta_title_ar,excerpt_en,excerpt_ar,body_en,body_ar,cover_image,published_at,is_published) values ($q$export-markets-uae-ksa-iraq$q$,$q$4U Power Generation's Export Markets: UAE, KSA & Iraq$q$,$q$أسواق التصدير لدى فوريو باور جينيريشن: الإمارات والسعودية والعراق$q$,$q$Generator Export from UAE to Saudi Arabia & Iraq | 4U Power$q$,$q$تصدير المولدات من الإمارات إلى السعودية والعراق | فوريو باور$q$,$q$Why we are based in SAIF Zone, Sharjah, and how we deliver generators and panels to the UAE, Saudi Arabia and Iraq — plus Qatar, Kenya and South Africa.$q$,$q$لماذا أسسنا أعمالنا في المنطقة الحرة لمطار الشارقة، وكيف نوصل المولدات واللوحات إلى الإمارات والسعودية والعراق، إضافة إلى قطر وكينيا وجنوب أفريقيا.$q$,$q$4U Power Generation FZC was licensed in SAIF Zone, Sharjah in August 2023 with one clear idea: the UAE is the best place in the region to stock, configure and ship power equipment quickly. Here is how that works for each of our core markets.

## Why SAIF Zone, Sharjah

- **Free-zone status** allows us to import engines, alternators and switchgear components and re-export them efficiently.
- **Location:** minutes from Sharjah International Airport, close to Khalid Port and an easy drive to Jebel Ali and the Saudi border.
- **Warehouse:** our 600 m² facility at Warehouse A2-020 holds popular generator ratings and panels ready for dispatch.

## United Arab Emirates — our home market

UAE customers benefit most directly: stock generators and ATS panels reach Sharjah, Dubai and Ajman within days, and Abu Dhabi and the northern emirates shortly after. Panels can be configured to DEWA, SEWA, ADDC/TAQA or FEWA requirements. [See our UAE page](/en/markets/uae).

## Saudi Arabia — overland in days

Saudi Arabia's construction and industrial activity makes it our fastest-growing market. Road freight via the Ghuwaifat/Batha border typically reaches Riyadh and Dammam within a week, avoiding sea-freight lead times. We supply 60 Hz-configured sets where required and prepare documentation for customs and SASO/SABER processes with your clearing agent. [See our Saudi Arabia page](/en/markets/saudi-arabia).

## Iraq — built for long run hours

In Iraq, generators often carry sites for many hours every day. We focus on prime-rated engines, larger fuel tanks and synchronised multi-generator plants. Shipments go by sea to Umm Qasr or overland to Baghdad, Erbil and the Kurdistan Region. [See our Iraq page](/en/markets/iraq).

## Qatar, Kenya and South Africa

- **Qatar:** by road via Saudi Arabia or by sea to Hamad Port.
- **Kenya:** sea freight to Mombasa — with strong demand for solar-hybrid systems.
- **South Africa:** sea freight to Durban — where load-shedding has turned standby sets into daily-use equipment.

## What every export order includes

- written quotation with Incoterms and confirmed lead time
- datasheets and factory test report
- commercial invoice, packing list and certificate of origin
- WhatsApp updates from order to dispatch

Planning a project in one of these markets? Send us the kVA or load list on WhatsApp — or browse [all markets we serve](/en/markets).$q$,$q$حصلت فوريو باور جينيريشن (ش.م.ح) على ترخيصها في المنطقة الحرة لمطار الشارقة في أغسطس 2023 بفكرة واضحة: الإمارات هي أفضل مكان في المنطقة لتخزين معدات الطاقة وتجهيزها وشحنها بسرعة. هكذا نخدم كل سوق من أسواقنا الرئيسية.

## لماذا المنطقة الحرة لمطار الشارقة؟

- **وضع المنطقة الحرة** يتيح لنا استيراد المحركات والدينامو ومكونات اللوحات وإعادة تصديرها بكفاءة.
- **الموقع:** دقائق من مطار الشارقة الدولي، وقريب من ميناء خالد، ومسافة قصيرة إلى جبل علي والحدود السعودية.
- **المستودع:** منشأتنا بمساحة 600 م² في المستودع A2-020 تضم القدرات الشائعة من المولدات واللوحات الجاهزة للشحن.

## الإمارات — سوقنا الأساسي

يستفيد عملاء الإمارات بشكل مباشر: المولدات ولوحات ATS المتوفرة تصل إلى الشارقة ودبي وعجمان خلال أيام، وأبوظبي والإمارات الشمالية بعدها بقليل. ويمكن تجهيز اللوحات حسب متطلبات ديوا وسيوا وأدك/طاقة واتحاد الماء والكهرباء. [اطلع على صفحة الإمارات](/ar/markets/uae).

## السعودية — شحن بري خلال أيام

نشاط الإنشاءات والصناعة في المملكة يجعلها أسرع أسواقنا نمواً. الشحن البري عبر منفذ الغويفات/البطحاء يصل عادةً إلى الرياض والدمام خلال أسبوع، دون انتظار الشحن البحري. نورد مولدات مهيأة لتردد 60 هرتز عند الحاجة، ونجهز المستندات للتخليص ومتطلبات ساسو/سابر مع مخلّصك الجمركي. [اطلع على صفحة السعودية](/ar/markets/saudi-arabia).

## العراق — مصممة لساعات التشغيل الطويلة

في العراق تحمل المولدات المواقع لساعات طويلة كل يوم، لذلك نركز على محركات بقدرة أساسية وخزانات وقود أكبر ومحطات متعددة المولدات متزامنة. يتم الشحن بحراً إلى أم قصر أو برّاً إلى بغداد وأربيل وإقليم كردستان. [اطلع على صفحة العراق](/ar/markets/iraq).

## قطر وكينيا وجنوب أفريقيا

- **قطر:** برّاً عبر السعودية أو بحراً إلى ميناء حمد.
- **كينيا:** شحن بحري إلى مومباسا، مع طلب قوي على الأنظمة الشمسية الهجينة.
- **جنوب أفريقيا:** شحن بحري إلى ديربان، حيث حوّل تخفيف الأحمال المولدات الاحتياطية إلى معدات للاستخدام اليومي.

## ما يتضمنه كل طلب تصدير

- عرض سعر مكتوب مع شروط الشحن (Incoterms) ومدة تسليم مؤكدة
- النشرات الفنية وتقرير الاختبار
- الفاتورة التجارية وقائمة التعبئة وشهادة المنشأ
- متابعة عبر الواتساب من الطلب حتى الشحن

تخطط لمشروع في أحد هذه الأسواق؟ أرسل لنا القدرة أو قائمة الأحمال على الواتساب، أو تصفح [جميع الأسواق التي نخدمها](/ar/markets).$q$,$q$/images/news/export-markets.svg$q$,$q$2026-09-01T08:00:00Z$q$,true) on conflict (slug) do nothing;
commit;
