-- AUTO-GENERATED by scripts/generate-seed.ts — do not edit by hand. Run files in numeric order.
begin;
insert into public.news_posts (slug,title_en,title_ar,meta_title_en,meta_title_ar,excerpt_en,excerpt_ar,body_en,body_ar,cover_image,published_at,is_published) values ($q$generator-price-uae-cost-factors$q$,$q$Generator Price in the UAE: What Really Decides the Cost$q$,$q$سعر المولد الكهربائي في الإمارات: ما الذي يحدد التكلفة فعلاً؟$q$,$q$Generator Price in UAE: 9 Factors That Decide Cost | 4U Power$q$,$q$سعر المولد في الإمارات: 9 عوامل تحدد التكلفة | فور يو باور$q$,$q$Two quotes for the same kVA can differ widely. The nine factors that really set a generator's price in the UAE, and how to compare quotations fairly.$q$,$q$قد يختلف عرضا سعر لنفس القدرة كثيراً. إليك العوامل التسعة التي تحدد سعر المولد الكهربائي فعلاً في الإمارات، وكيف تقارن عروض الأسعار بشكل عادل.$q$,$q$"How much is a 200 kVA generator?" is the most common question we get on WhatsApp — and the honest answer is: it depends on nine things. Two quotations for the same kVA can be far apart because they are not quoting the same machine. Here is what actually moves the price, so you can compare offers like for like.

## 1. The kVA rating — and whether it is standby or prime

Size is the biggest driver: a 500 kVA set costs far more than a 100 kVA one. But check **which rating** the quote uses. A "500 kVA" standby set delivers roughly 450 kVA on prime duty. If one supplier quotes standby and another quotes prime, the cheaper offer may simply be a smaller machine. Our guide to [prime vs standby ratings](/en/news/prime-vs-standby-generator-rating) explains the difference.

## 2. Engine brand

Perkins, Cummins, Volvo Penta, Baudouin, Kubota, Lister Petter and Chinese engine series all sit at different price points. Premium brands cost more up front but usually win on parts availability across the GCC, resale value and service network. See how they compare in [Perkins vs Cummins vs Kubota](/en/news/perkins-vs-cummins-vs-kubota-engine-brand-uae).

## 3. The alternator

The alternator turns engine power into electricity. Brand, insulation class (H is standard for the Gulf), winding pitch and the quality of the voltage regulator (AVR) all matter — especially if you feed sensitive IT equipment or VFDs.

## 4. Enclosure: open, silent canopy or container

- **Open frame** — cheapest, for plant rooms.
- **Silent canopy** — weatherproof and sound-attenuated; essential for villas, hospitals and residential areas.
- **Container** — for large sets and remote sites, with fuel and switchgear inside.

The quieter the canopy (measured in dB(A) at 7 m), the more steel and insulation it needs.

## 5. Controller and monitoring

A manual start panel is cheap. An **AMF controller** (Deep Sea or ComAp) that starts the set automatically on mains failure, with remote monitoring and alarms, costs more and is worth it for any standby application.

## 6. ATS and distribution panels

A generator only takes over automatically with an **automatic transfer switch**. Some quotes include it, many do not. Check the ATS rating matches the generator's full-load current — see [ATS panels explained](/en/news/ats-panels-explained).

## 7. Fuel tank size

A standard base tank typically gives around 8 hours at 75% load. Longer autonomy needs a bigger base tank or an external [fuel tank](/en/products/generator-fuel-tanks) — more steel, more cost.

## 8. Site conditions

At 50 °C ambient, engines and alternators lose output. A set specified for Gulf conditions needs a larger radiator and sometimes a bigger engine to deliver the same kVA. A quote that ignores derating is cheaper on paper only.

## 9. Delivery, installation, commissioning and warranty

Transport, offloading, cabling, exhaust extension, commissioning, load-bank testing and warranty can add a meaningful amount. Every product we supply carries a **12-month warranty**, and we quote installation and testing as separate, clear lines.

## How to compare two quotations

Put them side by side and check:

- the same **rating basis** (standby or prime) and the same kVA at your site temperature
- engine **and** alternator make and model
- enclosure type and noise level
- controller model and whether an ATS is included
- fuel tank capacity in hours
- what is included: delivery, installation, testing, warranty length

## Get an exact price

Use the [generator size chart](/en/generators/sizes) or the [kVA calculator](/en/calculator) to find your size, then send it to us on WhatsApp. We reply with options and a clear price breakdown — usually the same working day.$q$,$q$"بكم سعر مولد 200 ك.ف.أ؟" هو أكثر سؤال يصلنا على الواتساب، والإجابة الصادقة أنه يعتمد على تسعة عوامل. قد يختلف عرضا سعر لنفس القدرة كثيراً لأنهما لا يقدمان نفس الماكينة أصلاً. إليك ما يحرك السعر فعلاً حتى تقارن العروض بشكل عادل.

## 1. القدرة بالكيلو فولت أمبير، وهل هي احتياطية أم أساسية

الحجم هو العامل الأكبر؛ فمولد 500 ك.ف.أ أغلى بكثير من مولد 100 ك.ف.أ. لكن تأكد من **نوع التقنين** المذكور في العرض. المولد الاحتياطي "500 ك.ف.أ" يعطي نحو 450 ك.ف.أ في التشغيل الأساسي. إذا قدّم مورد قدرة احتياطية وآخر قدرة أساسية، فقد يكون العرض الأرخص مجرد ماكينة أصغر. مقالنا عن [الفرق بين القدرة الأساسية والاحتياطية](/ar/news/prime-vs-standby-generator-rating) يشرح ذلك.

## 2. ماركة المحرك

بيركنز وكمنز وفولفو بنتا وبودوان وكوبوتا وليستر بيتر والمحركات الصينية لكل منها مستوى سعري مختلف. الماركات الأعلى تكلف أكثر في البداية، لكنها غالباً تتفوق في توفر قطع الغيار في الخليج وقيمة إعادة البيع وشبكة الصيانة. اطلع على المقارنة في [بيركنز أم كمنز أم كوبوتا](/ar/news/perkins-vs-cummins-vs-kubota-engine-brand-uae).

## 3. الدينامو (المولّد الكهربائي)

الدينامو يحوّل قدرة المحرك إلى كهرباء. الماركة وفئة العزل (فئة H هي المعيار في الخليج) وجودة منظم الجهد (AVR) كلها مهمة، خاصة إذا كنت تغذي أجهزة حساسة أو مغيرات سرعة.

## 4. الهيكل: مفتوح أم كابينة صامتة أم حاوية

- **إطار مفتوح**: الأرخص، لغرف المولدات.
- **كابينة صامتة**: مقاومة للعوامل الجوية وعازلة للصوت، ضرورية للفلل والمستشفيات والمناطق السكنية.
- **حاوية**: للمولدات الكبيرة والمواقع البعيدة، مع الوقود واللوحات بداخلها.

كلما كانت الكابينة أهدأ (تقاس بالديسيبل على بعد 7 أمتار) احتاجت حديداً وعزلاً أكثر.

## 5. وحدة التحكم والمراقبة

لوحة التشغيل اليدوي رخيصة. أما **وحدة التحكم AMF** (ديب سي أو كوم آب) التي تشغّل المولد تلقائياً عند انقطاع الكهرباء مع مراقبة وإنذارات عن بُعد، فتكلف أكثر وتستحق ذلك في أي استخدام احتياطي.

## 6. لوحة ATS ولوحات التوزيع

لا يتولى المولد التغذية تلقائياً إلا مع **لوحة تحويل أوتوماتيكي**. بعض العروض تشملها وكثير منها لا. تأكد أن سعة اللوحة تناسب تيار الحمل الكامل للمولد. راجع [شرح لوحات ATS](/ar/news/ats-panels-explained).

## 7. سعة خزان الوقود

الخزان القاعدي القياسي يعطي عادةً نحو 8 ساعات عند حمل 75%. التشغيل الأطول يحتاج خزاناً قاعدياً أكبر أو [خزان وقود خارجي](/ar/products/generator-fuel-tanks)، أي حديداً وتكلفة أكثر.

## 8. ظروف الموقع

في حرارة 50 درجة يفقد المحرك والدينامو جزءاً من قدرتهما. المولد المجهز لظروف الخليج يحتاج مبرداً أكبر وأحياناً محركاً أكبر ليعطي نفس القدرة. العرض الذي يتجاهل خفض القدرة أرخص على الورق فقط.

## 9. التوصيل والتركيب والتشغيل والضمان

النقل والتنزيل والكابلات وتمديد العادم والتشغيل الأولي واختبار الحمل والضمان قد تضيف مبلغاً ملحوظاً. كل منتج نورّده مشمول **بضمان 12 شهراً**، ونقدم التركيب والاختبار كبنود منفصلة وواضحة.

## كيف تقارن بين عرضَي سعر

ضع العرضين جنباً إلى جنب وتأكد من:

- نفس **أساس التقنين** (احتياطي أم أساسي) ونفس القدرة عند حرارة موقعك
- ماركة وموديل المحرك **والدينامو**
- نوع الهيكل ومستوى الضوضاء
- موديل وحدة التحكم وهل لوحة ATS مشمولة
- سعة خزان الوقود بالساعات
- ما يشمله العرض: التوصيل والتركيب والاختبار ومدة الضمان

## احصل على سعر دقيق

استخدم [جدول أحجام المولدات](/ar/generators/sizes) أو [حاسبة القدرة](/ar/calculator) لتحديد الحجم، ثم أرسله لنا على الواتساب. نرد بالخيارات وتفصيل واضح للسعر، عادةً في نفس يوم العمل.$q$,$q$/images/products/perkins-diesel-generator-4u.webp$q$,$q$2026-10-06T06:00:00Z$q$,true) on conflict (slug) do nothing;
insert into public.news_posts (slug,title_en,title_ar,meta_title_en,meta_title_ar,excerpt_en,excerpt_ar,body_en,body_ar,cover_image,published_at,is_published) values ($q$generator-size-for-villa-uae$q$,$q$What Size Generator Does a Villa Need in the UAE?$q$,$q$ما حجم المولد المناسب للفيلا في الإمارات؟$q$,$q$Generator Size for a Villa in the UAE: kVA Guide | 4U Power$q$,$q$حجم مولد الفيلا في الإمارات: دليل اختيار القدرة | فور يو باور$q$,$q$In the Gulf, air-conditioning sizes a villa generator. How to count split units, pumps and kitchen loads, with a worked example and typical kVA ranges.$q$,$q$في الخليج، التكييف هو ما يحدد حجم مولد الفيلا. كيف تحسب وحدات السبليت والمضخات وأحمال المطبخ، مع مثال محسوب وأحجام القدرة المعتادة للفلل.$q$,$q$In a UAE villa the generator is sized by one thing above all: **air-conditioning**. Lighting, sockets and the fridge are small. Ten split units starting on a 46 °C afternoon are not. Here is how to size it properly.

## First decide: whole house or essential loads?

- **Essential loads only** — a few AC units (bedrooms), lighting, fridge, water pump, internet and CCTV. Smaller, cheaper and quieter.
- **Whole house** — everything runs as normal during an outage, including all AC and the kitchen. Larger set, bigger fuel tank.

Most families choose essential loads plus the master bedroom and living room AC.

## Step 1: Count the air-conditioning

A 2-ton split unit draws roughly **2.4 kW** while running. Count your units and their tonnage:

- 1.5-ton unit ≈ 1.8 kW
- 2-ton unit ≈ 2.4 kW
- 3-ton unit ≈ 3.6 kW

Inverter units start gently; older fixed-speed units draw a short surge when the compressor starts, so leave headroom.

## Step 2: Add the other loads

- water pumps and pressure sets: 1–2 kW
- lighting and sockets: 3–5 kW
- kitchen (oven, cooktop, microwave — not all at once): 4–6 kW
- water heaters: 2–3 kW each if left on
- pool pump, lift or EV charger if you have them

## Step 3: Convert to kVA and add margin

kVA = kW ÷ 0.8, then add about **25%** for motor starting and Gulf heat.

## Worked example: a 5-bedroom villa, whole house

| Load | kW |
| --- | --- |
| 8 split units × 2 tons | 19.2 |
| water pump | 1.5 |
| lighting and sockets | 4 |
| kitchen | 5 |
| water heaters | 3 |
| **Total** | **32.7** |

32.7 kW ÷ 0.8 = 41 kVA, plus 25% ≈ 51 kVA → a **[60 kVA generator](/en/generators/60-kva)**.

The same villa on essential loads only (4 AC units, pump, lighting, fridge) lands around a **[30 kVA set](/en/generators/30-kva)**.

## Typical ranges we supply

- essential loads, apartment or small villa: **15–30 kVA**
- full villa with 6–10 split units: **40–80 kVA**
- large villa or palace with ducted AC, pool and lift: **100–200 kVA**

## Three things villa owners often forget

1. **Noise.** Choose a silent canopy and check the dB(A) rating; your neighbours and community will thank you. Compact [Kubota](/en/products/kubota-silent-generator-10-40kva) and [Lister Petter](/en/products/lister-petter-generator-7-60kva) sets are built for this.
2. **Automatic changeover.** Without an [ATS panel](/en/ats-panels) someone has to start the set and switch over by hand — usually at 3 am.
3. **Single or three phase.** Most UAE villas have a three-phase 400/230 V supply; the generator must match.

## Get it right first time

Run your own numbers in the [kVA calculator](/en/calculator), or send us a photo of your DB board and a list of AC units on WhatsApp. We will recommend the size, canopy and ATS — and deliver across [Dubai](/en/locations/dubai), [Abu Dhabi](/en/locations/abu-dhabi) and the northern emirates.$q$,$q$في فيلا بالإمارات يُحدَّد حجم المولد بعامل واحد قبل كل شيء: **التكييف**. الإنارة والمقابس والثلاجة أحمال صغيرة، أما عشر وحدات سبليت تبدأ العمل في ظهيرة حرارتها 46 درجة فليست كذلك. إليك طريقة اختيار الحجم الصحيح.

## أولاً: الفيلا كلها أم الأحمال الأساسية فقط؟

- **الأحمال الأساسية فقط**: بعض وحدات التكييف (غرف النوم) والإنارة والثلاجة ومضخة المياه والإنترنت والكاميرات. مولد أصغر وأرخص وأهدأ.
- **الفيلا كلها**: كل شيء يعمل كالمعتاد أثناء الانقطاع بما فيه كل التكييف والمطبخ. مولد أكبر وخزان وقود أكبر.

معظم العائلات تختار الأحمال الأساسية مع تكييف غرفة النوم الرئيسية والصالة.

## الخطوة 1: احسب التكييف

وحدة السبليت 2 طن تسحب نحو **2.4 كيلوواط** أثناء التشغيل. احسب عدد وحداتك وقدرتها:

- وحدة 1.5 طن ≈ 1.8 كيلوواط
- وحدة 2 طن ≈ 2.4 كيلوواط
- وحدة 3 طن ≈ 3.6 كيلوواط

وحدات الإنفرتر تبدأ بهدوء، أما الوحدات القديمة ثابتة السرعة فتسحب تياراً لحظياً عند بدء الكمبروسر، لذا اترك هامشاً.

## الخطوة 2: أضف الأحمال الأخرى

- مضخات المياه ومجموعات الضغط: 1–2 كيلوواط
- الإنارة والمقابس: 3–5 كيلوواط
- المطبخ (فرن وموقد وميكروويف، ليست كلها معاً): 4–6 كيلوواط
- سخانات المياه: 2–3 كيلوواط لكل سخان إذا تُركت تعمل
- مضخة المسبح أو المصعد أو شاحن السيارة الكهربائية إن وُجدت

## الخطوة 3: حوّل إلى ك.ف.أ وأضف الهامش

ك.ف.أ = الكيلوواط ÷ 0.8، ثم أضف نحو **25%** لبدء المحركات وحرارة الخليج.

## مثال محسوب: فيلا 5 غرف، تغذية كاملة

| الحمل | كيلوواط |
| --- | --- |
| 8 وحدات سبليت × 2 طن | 19.2 |
| مضخة المياه | 1.5 |
| الإنارة والمقابس | 4 |
| المطبخ | 5 |
| سخانات المياه | 3 |
| **الإجمالي** | **32.7** |

32.7 كيلوواط ÷ 0.8 = 41 ك.ف.أ، مع 25% ≈ 51 ك.ف.أ ← **[مولد 60 ك.ف.أ](/ar/generators/60-kva)**.

نفس الفيلا مع الأحمال الأساسية فقط (4 وحدات تكييف ومضخة وإنارة وثلاجة) تحتاج نحو **[مولد 30 ك.ف.أ](/ar/generators/30-kva)**.

## الأحجام المعتادة التي نوردها

- أحمال أساسية لشقة أو فيلا صغيرة: **15–30 ك.ف.أ**
- فيلا كاملة بها 6–10 وحدات سبليت: **40–80 ك.ف.أ**
- فيلا كبيرة أو قصر بتكييف مركزي ومسبح ومصعد: **100–200 ك.ف.أ**

## ثلاثة أمور ينساها أصحاب الفلل

1. **الضوضاء.** اختر كابينة صامتة وتأكد من مستوى الديسيبل، وسيشكرك جيرانك. مولدات [كوبوتا](/ar/products/kubota-silent-generator-10-40kva) و[ليستر بيتر](/ar/products/lister-petter-generator-7-60kva) الصغيرة مصممة لذلك.
2. **التحويل التلقائي.** بدون [لوحة ATS](/ar/ats-panels) يجب أن يشغّل أحدهم المولد ويحوّل التغذية يدوياً، وغالباً في الثالثة فجراً.
3. **طور واحد أم ثلاثة أطوار.** معظم فلل الإمارات بها تغذية ثلاثية الأطوار 400/230 فولت، ويجب أن يطابقها المولد.

## اختر الحجم الصحيح من أول مرة

احسب بنفسك في [حاسبة القدرة](/ar/calculator)، أو أرسل لنا على الواتساب صورة لوحة التوزيع وقائمة وحدات التكييف. سنقترح الحجم والكابينة ولوحة ATS، ونوصل إلى [دبي](/ar/locations/dubai) و[أبوظبي](/ar/locations/abu-dhabi) والإمارات الشمالية.$q$,$q$/images/products/kubota-diesel-generator-4u.webp$q$,$q$2026-10-06T06:00:00Z$q$,true) on conflict (slug) do nothing;
commit;
