-- AUTO-GENERATED by scripts/generate-seed.ts — do not edit by hand. Run files in numeric order.
begin;
insert into public.news_posts (slug,title_en,title_ar,meta_title_en,meta_title_ar,excerpt_en,excerpt_ar,body_en,body_ar,cover_image,published_at,is_published) values ($q$prime-vs-standby-generator-rating$q$,$q$Prime vs Standby Generator Ratings: Which One Do You Need?$q$,$q$القدرة الأساسية أم الاحتياطية للمولد: أيهما تحتاج؟$q$,$q$Prime vs Standby Generator Rating Explained | 4U Power UAE$q$,$q$الفرق بين القدرة الأساسية والاحتياطية للمولد | فور يو باور$q$,$q$A 500 kVA standby set is not a 500 kVA prime set. What ISO 8528 standby, prime and continuous ratings mean, and why it matters on Gulf sites.$q$,$q$مولد 500 ك.ف.أ احتياطي ليس مولد 500 ك.ف.أ أساسي. ما معنى التقنين الاحتياطي والأساسي والمستمر حسب ISO 8528، ولماذا يهم ذلك في مواقع الخليج.$q$,$q$Every generator datasheet shows two or three power figures. Mixing them up is the most common — and most expensive — mistake in generator buying. Here is what each rating means under **ISO 8528-1**, and which one your project needs.

## Emergency standby power (ESP)

The highest number on the datasheet. It is the power the set can deliver **when the mains has failed**, for a limited number of hours per year (typically up to around 200), with an average load over 24 hours of no more than about 70% of the standby rating. There is **no overload capability** above it.

Use standby when the generator is a backup for a reliable grid: offices, towers, villas, schools, hotels in the UAE.

## Prime power (PRP)

Prime is the power the set can deliver for an **unlimited number of hours** per year with a varying load, again with the 24-hour average kept to about 70% of the prime rating. Most manufacturers allow a **10% overload for one hour in every twelve** on prime.

Prime is typically about **10% lower** than standby for the same machine. A set sold as "500 kVA standby" is roughly a 450 kVA prime set.

Use prime when the generator **is** the power supply — or runs many hours a day:

- construction sites and camps with no grid connection
- farms, quarries and remote sites
- markets with long daily outages, such as [Baghdad](/en/locations/baghdad) or [Basra](/en/locations/basra)

## Continuous power (COP)

A lower rating again, for a **constant 100% load** running without limit — base-load power plants and some industrial processes. Data centres often ask for a data-centre continuous rating; tell us if your consultant specifies one.

## Why it matters when you compare quotes

If supplier A quotes 500 kVA standby and supplier B quotes 500 kVA prime, supplier B is offering a **bigger machine** — so it will cost more. Always ask which rating a price refers to, and compare like with like. It is one of the [nine factors that decide generator price](/en/news/generator-price-uae-cost-factors).

## Heat changes the numbers too

Ratings are given at standard reference conditions. At 45–50 °C the engine and alternator must be derated, so in the Gulf we check the **site rating** at your real ambient temperature, not just the catalogue figure.

## Quick rule

- **Grid is reliable, generator is backup** → size on standby.
- **Generator runs daily or is the only supply** → size on prime, and allow for heat.

Our [generator size pages](/en/generators/sizes) show both the standby kVA and the matching prime figure for every size from 10 to 2500 kVA. Not sure which applies? Send us your run hours and load list on WhatsApp.$q$,$q$كل نشرة فنية لمولد تعرض رقمين أو ثلاثة للقدرة، والخلط بينها هو أكثر الأخطاء شيوعاً وتكلفة عند شراء المولد. إليك معنى كل تقنين حسب المعيار **ISO 8528-1**، وأيها يحتاجه مشروعك.

## القدرة الاحتياطية للطوارئ (ESP)

أعلى رقم في النشرة الفنية. هي القدرة التي يعطيها المولد **عند انقطاع الكهرباء العمومية**، لعدد محدود من الساعات سنوياً (عادةً حتى نحو 200 ساعة)، على ألا يتجاوز متوسط الحمل خلال 24 ساعة نحو 70% من القدرة الاحتياطية. **لا توجد قدرة تحميل زائد** فوقها.

استخدم التقنين الاحتياطي عندما يكون المولد بديلاً لشبكة كهرباء موثوقة: المكاتب والأبراج والفلل والمدارس والفنادق في الإمارات.

## القدرة الأساسية (PRP)

هي القدرة التي يعطيها المولد **لعدد غير محدود من الساعات** سنوياً مع حمل متغير، مع بقاء متوسط الحمل خلال 24 ساعة عند نحو 70% من القدرة الأساسية. تسمح معظم الشركات المصنعة **بحمل زائد 10% لمدة ساعة كل اثنتي عشرة ساعة** في التشغيل الأساسي.

القدرة الأساسية أقل عادةً **بنحو 10%** من الاحتياطية لنفس الماكينة. فالمولد المباع على أنه "500 ك.ف.أ احتياطي" هو تقريباً مولد 450 ك.ف.أ أساسي.

استخدم القدرة الأساسية عندما يكون المولد **هو** مصدر الكهرباء، أو يعمل ساعات طويلة يومياً:

- مواقع البناء والمخيمات غير المتصلة بالشبكة
- المزارع والمحاجر والمواقع البعيدة
- الأسواق ذات الانقطاعات اليومية الطويلة مثل [بغداد](/ar/locations/baghdad) و[البصرة](/ar/locations/basra)

## القدرة المستمرة (COP)

تقنين أقل أيضاً، لحمل **ثابت 100%** يعمل دون حد زمني، مثل محطات توليد الحمل الأساسي وبعض العمليات الصناعية. مراكز البيانات تطلب غالباً تقنيناً مستمراً خاصاً بها، فأخبرنا إذا كان استشاريك يحدده.

## لماذا يهم ذلك عند مقارنة العروض

إذا قدّم المورد (أ) 500 ك.ف.أ احتياطي وقدّم المورد (ب) 500 ك.ف.أ أساسي، فالمورد (ب) يعرض **ماكينة أكبر** وبالتالي أغلى. اسأل دائماً عن نوع التقنين الذي يشير إليه السعر وقارن المتماثل. وهو أحد [العوامل التسعة التي تحدد سعر المولد](/ar/news/generator-price-uae-cost-factors).

## الحرارة تغيّر الأرقام أيضاً

تُعطى القدرات عند ظروف مرجعية قياسية. في حرارة 45–50 درجة يجب خفض قدرة المحرك والدينامو، لذا نتحقق في الخليج من **قدرة الموقع** عند حرارتك الفعلية، لا من رقم الكتالوج فقط.

## قاعدة سريعة

- **الشبكة موثوقة والمولد احتياطي** ← اختر الحجم حسب القدرة الاحتياطية.
- **المولد يعمل يومياً أو هو المصدر الوحيد** ← اختر حسب القدرة الأساسية واحسب الحرارة.

[صفحات أحجام المولدات](/ar/generators/sizes) تعرض القدرة الاحتياطية والقدرة الأساسية المقابلة لكل حجم من 10 إلى 2500 ك.ف.أ. غير متأكد أيهما ينطبق عليك؟ أرسل لنا ساعات التشغيل وقائمة الأحمال على الواتساب.$q$,$q$/images/products/baudouin-containerized-generator-4u.webp$q$,$q$2026-10-06T06:00:00Z$q$,true) on conflict (slug) do nothing;
insert into public.news_posts (slug,title_en,title_ar,meta_title_en,meta_title_ar,excerpt_en,excerpt_ar,body_en,body_ar,cover_image,published_at,is_published) values ($q$generator-maintenance-checklist-gulf$q$,$q$Generator Maintenance Checklist for Gulf Heat and Dust$q$,$q$قائمة صيانة المولدات لحرارة وغبار الخليج$q$,$q$Generator Maintenance Checklist for UAE Heat & Dust | 4U Power$q$,$q$قائمة صيانة المولد في حرارة وغبار الخليج | فور يو باور$q$,$q$Heat, sand and long idle periods are what kill standby generators in the Gulf. A weekly, monthly and yearly checklist your facility team can follow.$q$,$q$الحرارة والرمال وفترات التوقف الطويلة هي ما يُتلف المولدات الاحتياطية في الخليج. قائمة صيانة أسبوعية وشهرية وسنوية يمكن لفريق المنشأة اتباعها.$q$,$q$A standby generator can sit idle for months and then must start within seconds and carry the full load on the hottest day of the year. In the Gulf, the usual reasons it fails are a flat battery, a blocked radiator, a clogged air filter or stale fuel. This checklist prevents all four.

## Weekly (10 minutes)

- walk round the set: look for oil, fuel and coolant leaks
- check fuel level and that the day tank is full
- check **battery voltage** and the charger is working — a weak battery is the number-one cause of failed starts
- confirm the controller is in **AUTO** with no active alarms
- check coolant level and that the jacket-water heater is warm (where fitted)

## Monthly

- **exercise run under load** for at least 30 minutes, ideally at 40% load or more; a no-load run does little good and encourages wet stacking
- check the air-filter restriction indicator; in dusty areas filters may need cleaning or changing far more often than the hours suggest
- clean the **radiator fins** — sand and dust packed between the fins are the main cause of overheating in summer
- inspect belts, hoses and clamps for cracks
- test the [ATS](/en/news/ats-panels-explained) by simulating a mains failure

## Every 250 hours or 6 months (whichever comes first)

- change engine oil and oil filter to the manufacturer's specification
- change fuel filters and drain water from the water separator
- check exhaust system, mounts and earthing

## Yearly

- **load-bank test** at up to full rated load to prove the set can carry its rating and to burn off carbon from light-load running — see our [load banks](/en/products/load-banks)
- coolant test and replacement as needed; check antifreeze/inhibitor concentration
- **fuel sampling** and, if needed, fuel polishing — diesel stored for long periods in heat degrades and grows bacteria
- check alternator insulation resistance and tighten electrical terminals
- full controller and protection check

## Warning signs to act on immediately

- black smoke under load (overload, injectors or air restriction)
- white smoke or oil around the exhaust (wet stacking from running lightly loaded)
- high coolant temperature alarms in summer (blocked radiator or fan belt)
- slow cranking (battery or starter)

## Let us do it for you

Our [maintenance contracts](/en/services) cover scheduled visits, filters and oil, load-bank testing and breakdown response across the UAE — for any brand, not only the sets we supply. Every new generator from us also carries a **12-month warranty**.$q$,$q$قد يبقى المولد الاحتياطي متوقفاً لشهور، ثم يُطلب منه أن يعمل خلال ثوانٍ ويحمل الحمل الكامل في أشد أيام السنة حرارة. في الخليج تكون أسباب تعطله المعتادة بطارية فارغة أو مبرد مسدود أو فلتر هواء متسخ أو وقود قديم. هذه القائمة تمنع الأسباب الأربعة.

## أسبوعياً (10 دقائق)

- تجول حول المولد وابحث عن تسريب زيت أو وقود أو سائل تبريد
- تأكد من مستوى الوقود وامتلاء الخزان اليومي
- افحص **جهد البطارية** وعمل الشاحن، فالبطارية الضعيفة هي السبب الأول لفشل التشغيل
- تأكد أن وحدة التحكم على وضع **AUTO** دون إنذارات نشطة
- افحص مستوى سائل التبريد ودفء سخان المياه إن وُجد

## شهرياً

- **تشغيل تجريبي تحت حمل** لمدة 30 دقيقة على الأقل، ويفضل بحمل 40% أو أكثر؛ التشغيل بدون حمل لا يفيد كثيراً ويسبب تراكم الوقود في العادم
- افحص مؤشر انسداد فلتر الهواء؛ في المناطق المغبرة قد تحتاج الفلاتر للتنظيف أو التغيير أسرع بكثير مما تشير إليه الساعات
- نظّف **زعانف المبرد**؛ فالرمال والغبار بين الزعانف هي السبب الرئيسي للسخونة الزائدة صيفاً
- افحص السيور والخراطيم والمرابط بحثاً عن تشققات
- اختبر [لوحة ATS](/ar/news/ats-panels-explained) بمحاكاة انقطاع الكهرباء

## كل 250 ساعة أو 6 أشهر (أيهما أقرب)

- غيّر زيت المحرك وفلتر الزيت حسب مواصفات الشركة المصنعة
- غيّر فلاتر الوقود واسحب الماء من فاصل المياه
- افحص نظام العادم والمساند والتأريض

## سنوياً

- **اختبار بحمل اختباري** حتى القدرة الكاملة لإثبات أن المولد يحمل قدرته المقننة ولحرق الكربون الناتج عن التشغيل بحمل خفيف. اطلع على [أحمال الاختبار](/ar/products/load-banks)
- فحص سائل التبريد واستبداله عند الحاجة، والتأكد من تركيز مانع التجمد والتآكل
- **أخذ عينة من الوقود** وتنقيته عند الحاجة، فالديزل المخزن طويلاً في الحرارة يتدهور وتنمو فيه البكتيريا
- فحص مقاومة عزل الدينامو وإحكام التوصيلات الكهربائية
- فحص شامل لوحدة التحكم والحمايات

## علامات تحذير تستدعي التدخل فوراً

- دخان أسود تحت الحمل (حمل زائد أو مشكلة في البخاخات أو انسداد الهواء)
- دخان أبيض أو زيت حول العادم (تراكم الوقود من التشغيل بحمل خفيف)
- إنذارات ارتفاع حرارة سائل التبريد صيفاً (مبرد مسدود أو سير مروحة)
- بطء دوران المحرك عند التشغيل (البطارية أو المارش)

## دعنا نتولاها عنك

[عقود الصيانة](/ar/services) لدينا تشمل زيارات مجدولة والفلاتر والزيت واختبار الحمل والاستجابة للأعطال في كل الإمارات، لأي ماركة وليس فقط المولدات التي نوردها. وكل مولد جديد من عندنا مشمول **بضمان 12 شهراً**.$q$,$q$/images/products/volvo-penta-diesel-generator-4u.webp$q$,$q$2026-10-13T06:00:00Z$q$,true) on conflict (slug) do nothing;
commit;
