-- AUTO-GENERATED by scripts/generate-seed.ts — do not edit by hand. Run files in numeric order.
begin;
insert into public.news_posts (slug,title_en,title_ar,meta_title_en,meta_title_ar,excerpt_en,excerpt_ar,body_en,body_ar,cover_image,published_at,is_published) values ($q$generator-installation-requirements-dubai$q$,$q$Installing a Generator in Dubai: Approvals and Site Checklist$q$,$q$تركيب مولد في دبي: الموافقات وقائمة متطلبات الموقع$q$,$q$Generator Installation in Dubai: Approvals Checklist | 4U Power$q$,$q$تركيب مولد في دبي: قائمة الموافقات والمتطلبات | فور يو باور$q$,$q$Who needs to approve a generator in Dubai, and what inspectors check: changeover interlocks, fuel storage, exhaust, ventilation and noise. A practical checklist.$q$,$q$من يوافق على تركيب مولد في دبي وماذا يفحص المفتشون: أقفال التحويل وتخزين الوقود والعادم والتهوية والضوضاء. قائمة عملية قبل التركيب.$q$,$q$A generator is not just delivered and switched on. In Dubai, a permanent standby set touches the electricity network, fuel storage, fire safety and the neighbours — so several parties have a say. Requirements change and differ by project type, so always confirm the current rules with your consultant and the authorities. This checklist covers what is typically reviewed.

## Who is usually involved

- **DEWA** — anything connected to the building's electrical installation, especially the changeover arrangement
- **Dubai Civil Defence** — fuel storage, fire safety and the generator room
- **Dubai Municipality** — location, exhaust and environmental aspects such as noise and emissions
- **The developer or community management** — many master communities and free zones have their own rules for placement and noise
- **Your MEP consultant** — prepares the drawings and submissions

## 1. No back-feed into the grid

The most important electrical rule: the generator must **never** be able to feed power back into the DEWA network. That is why the changeover must be done by a proper [ATS panel](/en/ats-panels) with **mechanical and electrical interlocking**, so mains and generator can never be connected at the same time. DIY changeover switches and plug-in arrangements are not acceptable for a permanent installation.

## 2. Fuel storage

Diesel is a fire risk, so expect checks on:

- tank capacity and location — larger volumes trigger more requirements
- **bunding** (a spill containment wall), commonly sized for at least 110% of the tank volume
- vents, fill points, level gauges and leak detection
- separation from ignition sources and building openings

Our [fuel tanks](/en/products/generator-fuel-tanks) are built with bunding and the fittings consultants expect.

## 3. Generator room or outdoor location

- adequate **ventilation** for combustion and cooling air — engines need a lot of it at 50 °C
- access for maintenance and for bringing in a load bank
- fire rating of walls and doors where the set is indoors
- a solid, level plinth with anti-vibration mounts

## 4. Exhaust

The exhaust should discharge where fumes cannot enter windows, air intakes or neighbouring buildings, usually above roof level with a suitable silencer and rain cap. Long exhaust runs need the right pipe size to avoid back-pressure.

## 5. Noise

In residential areas noise is the most common complaint. A **silent canopy** or an acoustically treated room, plus careful placement away from bedrooms, prevents problems with neighbours and community management. Ask for the canopy's dB(A) rating at 7 m.

## 6. Earthing and protection

The generator neutral and frame must be earthed according to the building's earthing system, with protection coordinated with the main distribution board.

## 7. Testing and handover

Expect a witnessed test: start-up, transfer on simulated mains failure, load test and protection checks. Keep the test report and as-built drawings for the inspectors.

## Let us prepare the package

We supply generators, ATS and distribution panels, fuel tanks and canopies with the datasheets, drawings and test certificates your consultant needs for submission — and we deliver across [Dubai](/en/locations/dubai). Send us your project details on WhatsApp.$q$,$q$المولد لا يُسلَّم ويُشغَّل فقط. في دبي يرتبط المولد الاحتياطي الدائم بشبكة الكهرباء وتخزين الوقود والسلامة من الحريق والجيران، لذلك تشارك فيه عدة جهات. المتطلبات تتغير وتختلف حسب نوع المشروع، فتأكد دائماً من القواعد الحالية مع استشاريك والجهات المختصة. هذه القائمة تغطي ما يُراجع عادةً.

## الجهات المعنية عادةً

- **هيئة كهرباء ومياه دبي (ديوا)**: كل ما يتصل بالتمديدات الكهربائية للمبنى، خاصة ترتيب التحويل
- **الدفاع المدني في دبي**: تخزين الوقود والسلامة من الحريق وغرفة المولد
- **بلدية دبي**: الموقع والعادم والجوانب البيئية مثل الضوضاء والانبعاثات
- **المطور أو إدارة المجتمع السكني**: كثير من المجتمعات والمناطق الحرة لها قواعدها الخاصة للموقع والضوضاء
- **الاستشاري الكهروميكانيكي**: يعد المخططات والمستندات المقدمة

## 1. منع التغذية العكسية للشبكة

أهم قاعدة كهربائية: يجب **ألا يتمكن** المولد أبداً من تغذية الكهرباء عكسياً إلى شبكة ديوا. لذلك يجب أن يتم التحويل عبر [لوحة ATS](/ar/ats-panels) مناسبة مع **أقفال ميكانيكية وكهربائية** تمنع توصيل الشبكة والمولد في نفس الوقت. مفاتيح التحويل المرتجلة وترتيبات القابس غير مقبولة في التركيب الدائم.

## 2. تخزين الوقود

الديزل خطر حريق، لذا توقع فحص:

- سعة الخزان وموقعه، فالكميات الأكبر تستدعي متطلبات أكثر
- **الحوض الواقي** (جدار احتواء التسرب)، ويكون عادةً بسعة 110% على الأقل من حجم الخزان
- فتحات التهوية ونقاط التعبئة ومؤشرات المستوى وكشف التسرب
- الابتعاد عن مصادر الاشتعال وفتحات المبنى

[خزانات الوقود](/ar/products/generator-fuel-tanks) لدينا مصنّعة بحوض واقٍ وبالتجهيزات التي يتوقعها الاستشاريون.

## 3. غرفة المولد أو الموقع الخارجي

- **تهوية** كافية لهواء الاحتراق والتبريد، فالمحركات تحتاج كمية كبيرة منه في حرارة 50 درجة
- مدخل للصيانة ولإدخال حمل الاختبار
- مقاومة الجدران والأبواب للحريق إذا كان المولد داخل المبنى
- قاعدة خرسانية مستوية مع مساند ماصة للاهتزاز

## 4. العادم

يجب أن يخرج العادم في مكان لا تدخل منه الأبخرة إلى النوافذ أو مداخل الهواء أو المباني المجاورة، وغالباً فوق مستوى السطح مع كاتم صوت وغطاء مطر مناسبين. مسارات العادم الطويلة تحتاج قطر أنبوب صحيح لتجنب الضغط العكسي.

## 5. الضوضاء

في المناطق السكنية تكون الضوضاء أكثر الشكاوى شيوعاً. **الكابينة الصامتة** أو الغرفة المعالجة صوتياً، مع اختيار موقع بعيد عن غرف النوم، تمنع المشاكل مع الجيران وإدارة المجتمع. اطلب مستوى الديسيبل للكابينة على بعد 7 أمتار.

## 6. التأريض والحماية

يجب تأريض محايد المولد وهيكله حسب نظام التأريض في المبنى، مع تنسيق الحمايات مع لوحة التوزيع الرئيسية.

## 7. الاختبار والتسليم

توقع اختباراً بحضور الجهات: التشغيل والتحويل عند محاكاة انقطاع الكهرباء واختبار الحمل وفحص الحمايات. احتفظ بتقرير الاختبار والمخططات النهائية للمفتشين.

## دعنا نجهز لك الملف

نورّد المولدات ولوحات ATS والتوزيع وخزانات الوقود والكبائن مع النشرات الفنية والمخططات وشهادات الاختبار التي يحتاجها استشاريك للتقديم، ونوصل إلى كل أنحاء [دبي](/ar/locations/dubai). أرسل لنا تفاصيل مشروعك على الواتساب.$q$,$q$/images/products/volvo-penta-containerized-generator-4u.webp$q$,$q$2026-10-15T06:00:00Z$q$,true) on conflict (slug) do nothing;
insert into public.news_posts (slug,title_en,title_ar,meta_title_en,meta_title_ar,excerpt_en,excerpt_ar,body_en,body_ar,cover_image,published_at,is_published) values ($q$generator-fuel-consumption-chart$q$,$q$Generator Fuel Consumption Chart: Litres per Hour from 20 to 2000 kVA$q$,$q$جدول استهلاك المولد للديزل: لتر في الساعة من 20 إلى 2000 ك.ف.أ$q$,$q$Generator Fuel Consumption Chart (L/h) 20–2000 kVA | 4U Power$q$,$q$جدول استهلاك المولد للديزل باللتر في الساعة | فور يو باور$q$,$q$How much diesel does a generator use per hour? A consumption chart from 20 to 2000 kVA at 50%, 75% and full load, plus how to size the fuel tank.$q$,$q$كم لتر ديزل يستهلك المولد في الساعة؟ جدول استهلاك من 20 إلى 2000 ك.ف.أ عند حمل 50% و75% والحمل الكامل، مع طريقة حساب سعة خزان الوقود.$q$,$q$Fuel is the biggest running cost of a generator, and it decides how big the tank must be. Here is how much diesel a set uses, and how to work out your own numbers.

## The quick rule

A modern diesel generator uses roughly **0.26 litres of diesel per kWh** produced at 75% load. Efficiency drops at light load and is slightly worse at full load.

**Litres per hour ≈ kW of load × 0.26**

So a 200 kVA set (160 kW) running at 75% load (120 kW) burns about 31 litres an hour.

## Consumption chart

Typical values for modern diesel sets at 0.8 power factor. Exact figures depend on engine model and site conditions — always check the datasheet for the unit quoted.

| Generator (kVA) | Prime kW | 50% load (L/h) | 75% load (L/h) | 100% load (L/h) |
| --- | --- | --- | --- | --- |
| 20 | 16 | 2.2 | 3.1 | 4.3 |
| 30 | 24 | 3.4 | 4.7 | 6.5 |
| 50 | 40 | 5.6 | 7.8 | 10.8 |
| 60 | 48 | 6.7 | 9.4 | 13.0 |
| 80 | 64 | 9.0 | 12.5 | 17.3 |
| 100 | 80 | 11.2 | 15.6 | 21.6 |
| 150 | 120 | 16.8 | 23.4 | 32.4 |
| 200 | 160 | 22.4 | 31.2 | 43.2 |
| 250 | 200 | 28.0 | 39.0 | 54.0 |
| 300 | 240 | 33.6 | 46.8 | 64.8 |
| 400 | 320 | 44.8 | 62.4 | 86.4 |
| 500 | 400 | 56.0 | 78.0 | 108.0 |
| 650 | 520 | 72.8 | 101.4 | 140.4 |
| 750 | 600 | 84.0 | 117.0 | 162.0 |
| 1000 | 800 | 112.0 | 156.0 | 216.0 |
| 1250 | 1000 | 140.0 | 195.0 | 270.0 |
| 1500 | 1200 | 168.0 | 234.0 | 324.0 |
| 2000 | 1600 | 224.0 | 312.0 | 432.0 |

Each size has its own page with the full specs — for example the [100 kVA](/en/generators/100-kva), [500 kVA](/en/generators/500-kva) and [1000 kVA](/en/generators/1000-kva) generators.

## What makes consumption go up

- **light loading** — a set at 20% load burns more fuel per kWh and suffers wet stacking
- **heat** — at 50 °C the radiator fan works harder and output is derated
- **dirty air filters and poor maintenance** — see our [maintenance checklist](/en/news/generator-maintenance-checklist-gulf)
- **oversizing** — a set far bigger than the load wastes fuel every hour it runs

## How to size the fuel tank

**Tank (litres) = L/h at expected load × hours of autonomy × 1.1**

The 10% covers the unusable fuel at the bottom of the tank. Example: a 500 kVA set at 75% load for 24 hours → 78 × 24 × 1.1 ≈ 2,060 litres. Standard base tanks usually give around 8 hours; longer autonomy needs a bigger base tank or an external [fuel tank](/en/products/generator-fuel-tanks).

## Running cost per hour

Multiply the litres per hour by the current diesel price. Over a year, 1–2 litres per hour saved by correct sizing adds up to thousands of litres — which is why getting the size right with our [kVA calculator](/en/calculator) pays for itself.$q$,$q$الوقود هو أكبر تكلفة تشغيل للمولد، وهو ما يحدد حجم الخزان المطلوب. إليك كمية الديزل التي يستهلكها المولد، وكيف تحسب أرقامك بنفسك.

## القاعدة السريعة

يستهلك مولد الديزل الحديث نحو **0.26 لتر ديزل لكل كيلوواط ساعة** عند حمل 75%. تقل الكفاءة عند الحمل الخفيف وتسوء قليلاً عند الحمل الكامل.

**اللتر في الساعة ≈ الحمل بالكيلوواط × 0.26**

فمولد 200 ك.ف.أ (160 كيلوواط) يعمل بحمل 75% (120 كيلوواط) يحرق نحو 31 لتراً في الساعة.

## جدول الاستهلاك

قيم نموذجية لمولدات الديزل الحديثة عند معامل قدرة 0.8. الأرقام الدقيقة تعتمد على موديل المحرك وظروف الموقع، فراجع دائماً النشرة الفنية للوحدة المعروضة.

| المولد (ك.ف.أ) | كيلوواط | حمل 50% (لتر/ساعة) | حمل 75% (لتر/ساعة) | حمل 100% (لتر/ساعة) |
| --- | --- | --- | --- | --- |
| 20 | 16 | 2.2 | 3.1 | 4.3 |
| 30 | 24 | 3.4 | 4.7 | 6.5 |
| 50 | 40 | 5.6 | 7.8 | 10.8 |
| 60 | 48 | 6.7 | 9.4 | 13.0 |
| 80 | 64 | 9.0 | 12.5 | 17.3 |
| 100 | 80 | 11.2 | 15.6 | 21.6 |
| 150 | 120 | 16.8 | 23.4 | 32.4 |
| 200 | 160 | 22.4 | 31.2 | 43.2 |
| 250 | 200 | 28.0 | 39.0 | 54.0 |
| 300 | 240 | 33.6 | 46.8 | 64.8 |
| 400 | 320 | 44.8 | 62.4 | 86.4 |
| 500 | 400 | 56.0 | 78.0 | 108.0 |
| 650 | 520 | 72.8 | 101.4 | 140.4 |
| 750 | 600 | 84.0 | 117.0 | 162.0 |
| 1000 | 800 | 112.0 | 156.0 | 216.0 |
| 1250 | 1000 | 140.0 | 195.0 | 270.0 |
| 1500 | 1200 | 168.0 | 234.0 | 324.0 |
| 2000 | 1600 | 224.0 | 312.0 | 432.0 |

لكل حجم صفحة خاصة بالمواصفات الكاملة، مثل مولد [100 ك.ف.أ](/ar/generators/100-kva) و[500 ك.ف.أ](/ar/generators/500-kva) و[1000 ك.ف.أ](/ar/generators/1000-kva).

## ما الذي يرفع الاستهلاك

- **الحمل الخفيف**: المولد عند حمل 20% يحرق وقوداً أكثر لكل كيلوواط ساعة ويعاني من تراكم الوقود في العادم
- **الحرارة**: في 50 درجة تعمل مروحة المبرد بجهد أكبر وتنخفض القدرة
- **فلاتر الهواء المتسخة وضعف الصيانة**: راجع [قائمة الصيانة](/ar/news/generator-maintenance-checklist-gulf)
- **الحجم الزائد**: المولد الأكبر بكثير من الحمل يهدر الوقود في كل ساعة تشغيل

## كيف تحسب سعة خزان الوقود

**سعة الخزان (لتر) = اللتر في الساعة عند الحمل المتوقع × ساعات التشغيل المطلوبة × 1.1**

نسبة 10% تغطي الوقود غير القابل للاستخدام في قاع الخزان. مثال: مولد 500 ك.ف.أ بحمل 75% لمدة 24 ساعة ← 78 × 24 × 1.1 ≈ 2,060 لتراً. الخزانات القاعدية القياسية تعطي عادةً نحو 8 ساعات، والتشغيل الأطول يحتاج خزاناً قاعدياً أكبر أو [خزان وقود خارجي](/ar/products/generator-fuel-tanks).

## تكلفة التشغيل في الساعة

اضرب اللترات في الساعة في سعر الديزل الحالي. على مدار سنة، توفير لتر أو لترين في الساعة بالحجم الصحيح يصل إلى آلاف اللترات، ولهذا فإن اختيار الحجم الصحيح عبر [حاسبة القدرة](/ar/calculator) يغطي تكلفته بنفسه.$q$,$q$/images/products/baudouin-diesel-generator-4u.webp$q$,$q$2026-10-19T06:00:00Z$q$,true) on conflict (slug) do nothing;
commit;
