-- AUTO-GENERATED by scripts/generate-seed.ts — do not edit by hand. Run files in numeric order.
begin;
insert into public.news_posts (slug,title_en,title_ar,meta_title_en,meta_title_ar,excerpt_en,excerpt_ar,body_en,body_ar,cover_image,published_at,is_published) values ($q$ats-panel-types-motorized-contactor-acb$q$,$q$ATS Panel Types: Contactor, Motorised Switch or ACB?$q$,$q$أنواع لوحات ATS: كونتاكتور أم مفتاح موتورايزد أم ACB؟$q$,$q$ATS Panel Types: Contactor vs Motorised vs ACB | 4U Power$q$,$q$أنواع لوحات ATS: كونتاكتور أم موتورايزد أم ACB | فور يو باور$q$,$q$Not all automatic transfer switches are built the same. Contactor, motorised and ACB-based ATS panels compared, plus 3-pole vs 4-pole and sizing.$q$,$q$لوحات التحويل الأوتوماتيكي ليست كلها متشابهة. مقارنة بين لوحات ATS بالكونتاكتور والمفتاح الموتورايزد والقاطع الهوائي ACB، مع 3 و4 أقطاب والسعة.$q$,$q$Every automatic transfer switch does the same job — move the load from mains to generator and back — but the switching device inside decides how big, how robust and how expensive the panel is. For the basics of how an ATS works, see [ATS panels explained](/en/news/ats-panels-explained). This guide compares the three main types.

## 1. Contactor-based ATS

Two electrically and mechanically interlocked **contactors**, one for mains and one for the generator.

- **Best for:** small and medium loads — villas, shops, telecom sites, small buildings
- **Pros:** fast switching, simple, economical, easy to maintain
- **Watch out for:** contactor rating must cover the full load current with margin; not the choice for very high fault levels

## 2. Motorised changeover switch (load-break switch)

A single **motor-operated changeover switch** with three positions: mains – off – generator. The mechanism itself makes it impossible to close both sides together.

- **Best for:** medium to large buildings, commercial and industrial sites
- **Pros:** inherent mechanical interlock, compact, wide range of ratings, can often be operated manually in an emergency
- **Watch out for:** the switch must be rated for the prospective fault current at the board

## 3. ACB-based ATS

Two **air circuit breakers** with motor operators and mechanical interlock — the heavy-duty option.

- **Best for:** large loads and main distribution boards, typically from around 800 A up to several thousand amps
- **Pros:** switching and protection in one device, high fault ratings, withdrawable for maintenance, adjustable protection settings
- **Watch out for:** larger panel and higher cost; justified at high currents

## 3-pole or 4-pole?

- **4-pole** switches the neutral as well. It is usually needed where the generator neutral is earthed separately, where there are multiple sources, or to avoid neutral currents flowing through the wrong path
- **3-pole** keeps a common, solid neutral — common in simple installations

The correct choice follows the building's earthing system; your consultant will specify it, and we build to that specification.

## Open or closed transition?

Standard ATS panels use **open transition**: the load is briefly disconnected while switching (break-before-make). **Closed transition** briefly parallels the two sources so the return to mains has no interruption; it needs synchronising control and utility approval, and is used for sensitive loads.

## Sizing the ATS

Rate the ATS to the generator's full-load current: at 400 V, **amps ≈ kVA × 1.44**. A 500 kVA generator needs about 720 A, so an 800 A ATS. Each [generator size page](/en/generators/sizes) shows the matching ATS rating.

## What we build

We supply [ATS panels](/en/ats-panels) from 63 A to 4000 A — contactor, motorised and ACB types, 3- or 4-pole — built and tested in Sharjah with AMF controllers and full documentation. Send us your generator size and single-line diagram on WhatsApp for a quote.$q$,$q$كل لوحة تحويل أوتوماتيكي تؤدي نفس المهمة، وهي نقل الحمل من الشبكة إلى المولد والعكس، لكن جهاز التحويل بداخلها هو ما يحدد حجم اللوحة ومتانتها وتكلفتها. لفهم أساسيات عمل اللوحة راجع [شرح لوحات ATS](/ar/news/ats-panels-explained). هذا الدليل يقارن الأنواع الثلاثة الرئيسية.

## 1. لوحة ATS بالكونتاكتور

**كونتاكتوران** بينهما قفل كهربائي وميكانيكي، واحد للشبكة وواحد للمولد.

- **الأنسب لـ:** الأحمال الصغيرة والمتوسطة، مثل الفلل والمحلات ومواقع الاتصالات والمباني الصغيرة
- **المزايا:** تحويل سريع وبسيط واقتصادي وسهل الصيانة
- **انتبه إلى:** يجب أن تغطي سعة الكونتاكتور تيار الحمل الكامل مع هامش، وهو ليس الخيار المناسب لمستويات القصر العالية جداً

## 2. مفتاح التحويل الموتورايزد

**مفتاح تحويل واحد يعمل بمحرك** بثلاثة أوضاع: الشبكة – إيقاف – المولد. تصميم الآلية نفسه يمنع توصيل الجانبين معاً.

- **الأنسب لـ:** المباني المتوسطة والكبيرة والمواقع التجارية والصناعية
- **المزايا:** قفل ميكانيكي مدمج وحجم صغير ونطاق واسع من السعات، وغالباً يمكن تشغيله يدوياً في الطوارئ
- **انتبه إلى:** يجب أن يكون المفتاح مقنناً لتيار القصر المتوقع في اللوحة

## 3. لوحة ATS بالقاطع الهوائي ACB

**قاطعان هوائيان** بمشغلات كهربائية وقفل ميكانيكي، وهو الخيار للخدمة الشاقة.

- **الأنسب لـ:** الأحمال الكبيرة ولوحات التوزيع الرئيسية، عادةً من نحو 800 أمبير حتى عدة آلاف من الأمبيرات
- **المزايا:** التحويل والحماية في جهاز واحد، وتحمل عالٍ لتيار القصر، وإمكانية السحب للصيانة، وإعدادات حماية قابلة للضبط
- **انتبه إلى:** لوحة أكبر وتكلفة أعلى، ويكون مبرراً عند التيارات العالية

## 3 أقطاب أم 4 أقطاب؟

- **4 أقطاب** تفصل المحايد أيضاً، وتكون مطلوبة عادةً عندما يُؤرَّض محايد المولد بشكل منفصل، أو عند وجود عدة مصادر، أو لمنع مرور تيارات المحايد في مسار خاطئ
- **3 أقطاب** تُبقي محايداً مشتركاً ثابتاً، وهي شائعة في التركيبات البسيطة

الاختيار الصحيح يتبع نظام التأريض في المبنى، ويحدده الاستشاري ونصنّع حسب مواصفاته.

## تحويل مفتوح أم مغلق؟

تستخدم لوحات ATS القياسية **التحويل المفتوح**، حيث ينقطع الحمل لحظياً أثناء التحويل (فصل قبل توصيل). أما **التحويل المغلق** فيوصل المصدرين على التوازي لحظياً فلا يحدث انقطاع عند العودة للشبكة، ويحتاج تحكماً بالتزامن وموافقة جهة الكهرباء، ويُستخدم للأحمال الحساسة.

## اختيار سعة اللوحة

اختر سعة اللوحة حسب تيار الحمل الكامل للمولد: على 400 فولت، **الأمبير ≈ ك.ف.أ × 1.44**. مولد 500 ك.ف.أ يحتاج نحو 720 أمبير، أي لوحة ATS سعة 800 أمبير. تعرض كل [صفحة من صفحات أحجام المولدات](/ar/generators/sizes) سعة اللوحة المناسبة.

## ما نصنّعه

نورّد [لوحات ATS](/ar/ats-panels) من 63 إلى 4000 أمبير، بالكونتاكتور أو الموتورايزد أو ACB، بـ 3 أو 4 أقطاب، مصنّعة ومختبرة في الشارقة مع وحدات تحكم AMF ومستندات كاملة. أرسل لنا حجم المولد والمخطط الأحادي على الواتساب لعرض سعر.$q$,$q$/images/products/perkins-containerized-generator-4u.webp$q$,$q$2026-10-22T06:00:00Z$q$,true) on conflict (slug) do nothing;
commit;
