/**
 * Generates supabase/seed.sql from the bundled content (src/content/*), so the database and the
 * offline fallback always start identical. Run: npm run seed:sql
 */
import { writeFileSync } from "node:fs";
import { products } from "../src/content/products";
import { projects, testimonials } from "../src/content/projects";
import { newsPosts } from "../src/content/news";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return v.length ? `array[${v.map(q).join(",")}]::text[]` : "'{}'::text[]";
  return `'${String(v).replace(/'/g, "''")}'`;
};
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const out: string[] = ["-- AUTO-GENERATED by scripts/generate-seed.ts — do not edit by hand.", "begin;"];

for (const p of products) {
  out.push(
    `insert into public.products (category,slug,name_en,name_ar,kva_min,kva_max,engine_brand,fuel_type,description_en,description_ar,specs,spec_sheet_url,images,sort_order,is_published) values (${[
      q(p.category), q(p.slug), q(p.name_en), q(p.name_ar), q(p.kva_min), q(p.kva_max), q(p.engine_brand), q(p.fuel_type),
      q(p.description_en), q(p.description_ar), json(p.specs), q(p.spec_sheet_url), q(p.images), q(p.sort_order), q(p.is_published),
    ].join(",")}) on conflict (slug) do nothing;`,
  );
}
for (const p of projects) {
  out.push(
    `insert into public.projects (slug,title_en,title_ar,country,sector,kva,summary_en,summary_ar,images,is_published) values (${[
      q(p.slug), q(p.title_en), q(p.title_ar), q(p.country), q(p.sector), q(p.kva), q(p.summary_en), q(p.summary_ar), q(p.images), q(p.is_published),
    ].join(",")}) on conflict (slug) do nothing;`,
  );
}
for (const t of testimonials) {
  out.push(
    `insert into public.testimonials (client_name,client_company,country,quote_en,quote_ar,rating,is_published) values (${[
      q(t.client_name), q(t.client_company), q(t.country), q(t.quote_en), q(t.quote_ar), q(t.rating), q(t.is_published),
    ].join(",")});`,
  );
}
for (const n of newsPosts) {
  out.push(
    `insert into public.news_posts (slug,title_en,title_ar,meta_title_en,meta_title_ar,excerpt_en,excerpt_ar,body_en,body_ar,cover_image,published_at,is_published) values (${[
      q(n.slug), q(n.title_en), q(n.title_ar), q(n.meta_title_en), q(n.meta_title_ar), q(n.excerpt_en), q(n.excerpt_ar),
      q(n.body_en), q(n.body_ar), q(n.cover_image), q(n.published_at), q(n.is_published),
    ].join(",")}) on conflict (slug) do nothing;`,
  );
}
out.push("commit;", "");
writeFileSync("supabase/seed.sql", out.join("\n"));
console.log(`seed.sql: ${products.length} products, ${projects.length} projects, ${testimonials.length} testimonials, ${newsPosts.length} posts`);
