/**
 * Generates supabase/seed/*.sql from the bundled content (src/content/*), so the database and the
 * offline fallback always start identical. Run: npm run seed:sql
 *
 * Output is split into small files (Supabase SQL editor paste limit) and uses dollar-quoted strings
 * so copy/paste can never break quoting. Every file is idempotent — safe to run twice.
 */
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { products } from "../src/content/products";
import { projects, testimonials } from "../src/content/projects";
import { newsPosts } from "../src/content/news";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return v.length ? `array[${v.map(q).join(",")}]::text[]` : "'{}'::text[]";
  const str = String(v);
  if (str.includes("$q$")) throw new Error("content contains $q$ delimiter");
  return `$q$${str}$q$`;
};
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const HEADER = "-- AUTO-GENERATED by scripts/generate-seed.ts — do not edit by hand. Run files in numeric order.";
const files: { name: string; rows: string[] }[] = [];
let out: string[] = [];
const file = (name: string) => {
  out = [];
  files.push({ name, rows: out });
};

file("01_products.sql");

for (const p of products) {
  out.push(
    `insert into public.products (category,slug,name_en,name_ar,kva_min,kva_max,engine_brand,fuel_type,description_en,description_ar,specs,spec_sheet_url,images,sort_order,is_published) values (${[
      q(p.category), q(p.slug), q(p.name_en), q(p.name_ar), q(p.kva_min), q(p.kva_max), q(p.engine_brand), q(p.fuel_type),
      q(p.description_en), q(p.description_ar), json(p.specs), q(p.spec_sheet_url), q(p.images), q(p.sort_order), q(p.is_published),
    ].join(",")}) on conflict (slug) do nothing;`,
  );
}
file("02_projects_testimonials.sql");
for (const p of projects) {
  out.push(
    `insert into public.projects (slug,title_en,title_ar,country,sector,kva,summary_en,summary_ar,images,is_published) values (${[
      q(p.slug), q(p.title_en), q(p.title_ar), q(p.country), q(p.sector), q(p.kva), q(p.summary_en), q(p.summary_ar), q(p.images), q(p.is_published),
    ].join(",")}) on conflict (slug) do nothing;`,
  );
}
for (const t of testimonials) {
  out.push(
    `insert into public.testimonials (client_name,client_company,country,quote_en,quote_ar,rating,is_published) select ${[
      q(t.client_name), q(t.client_company), q(t.country), q(t.quote_en), q(t.quote_ar), q(t.rating), q(t.is_published),
    ].join(",")} where not exists (select 1 from public.testimonials where quote_en = ${q(t.quote_en)});`,
  );
}
newsPosts.forEach((n, i) => {
  if (i % 2 === 0) file(`0${3 + i / 2}_news_${i / 2 + 1}.sql`);
  out.push(
    `insert into public.news_posts (slug,title_en,title_ar,meta_title_en,meta_title_ar,excerpt_en,excerpt_ar,body_en,body_ar,cover_image,published_at,is_published) values (${[
      q(n.slug), q(n.title_en), q(n.title_ar), q(n.meta_title_en), q(n.meta_title_ar), q(n.excerpt_en), q(n.excerpt_ar),
      q(n.body_en), q(n.body_ar), q(n.cover_image), q(n.published_at), q(n.is_published),
    ].join(",")}) on conflict (slug) do nothing;`,
  );
});

rmSync("supabase/seed", { recursive: true, force: true });
mkdirSync("supabase/seed", { recursive: true });
for (const f of files) {
  const sql = [HEADER, "begin;", ...f.rows, "commit;", ""].join("\n");
  writeFileSync(`supabase/seed/${f.name}`, sql);
  console.log(`supabase/seed/${f.name}  ${(sql.length / 1024).toFixed(1)} KB`);
}
